### PR TITLE
using the multi decorator and forwarder

### PR DESCRIPTION
**Pull request by tbeukhof**

### CODE REVIEW

**Comment by dgoetsch** [comment]
No tests? I hav to ask, does it run?

**Comment by dgoetsch** [comment]
I see now that a lot of the components are null in the config... Do you want this merged now, or should o wait until you add more?

**Comment by tbeukhof** [comment]
I know Nichole has a lot of the code locally, so I didn't want to duplicate that work. I was hoping she could fill in the Parser and MetadataCreator with what she has.

I took this as far as running it, setting a breakpoint in the EventProcessorService, hitting the process-event endpoint with the sample JSON for a SystemMidAuditEvent, and verifying the Autowired fields were set as I expected.

**Comment by tbeukhof** [comment]
Since Nichole is out today, I will start filling in the parser and metadata creator.

**Pull request closed without merging**
